9 sprint/1 review
Klementor/java-filmorate pull request #1
Opened 2022-09-19 13:56 UTC by Klementor

2022-09-19 17:39 UTC, Frilock requested changes
Добрый день, оставил пару комментариев к работе, жду новую версию.

2022-09-19 17:39 UTC, Frilock commented on pom.xml
> +            <version>1.18.20</version>
Тут 2 момента сразу:
1. Версия для lombok не нужна, поскольку данная библиотека есть в parent и она оттуда подтянетя
2. Если же все таки хотите указать версию (возможно она отличаться от той которая в parent должна для ваших целей), то правильнее версии библиотек, которые вы подключаете в pom файле, писать в preporties (по аналогии с версией java), поскольку pom файлы могут быть очень большого размера и изменение версии библиотеки может оказаться не такой простой задачей

2022-09-19 17:39 UTC, Frilock commented on pom.xml
> +            <version>4.13.2</version>
На мой взгляд лучше сразу использовать версию 5+, эта довольна старая

2022-09-19 17:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    Map<Long, User> users = new HashMap<>();
Модификатор забыли

2022-09-19 17:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +public class UserController {
Задание со звездочкой: вообще оба контроллера имеют одинаковую структуру и логику, можно создать абстрактный контролер, описать там базовую реализацию, а тут через дженерики от него наследоваться

2022-09-19 17:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Можете поиграться с аннотациями: для улучшения валидации, можно воспользоваться зависимостью
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-validation</artifactId>
</dependency>
В данном случае на поля класса модели можно повесить дополнительные аннотации, например,
@NotNull к полю для проверки на null, @NotBlank — для проверки на пустую строку, @Email — для проверки на соответствие формату электронного адреса.

2022-09-19 17:39 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/validator/FilmValidatorTest.java
> +    Film film;
Модификатор

2022-09-20 18:35 UTC, Frilock requested changes
Добрый вечер, не все поправили, отправил на доработку

2022-09-20 18:35 UTC, Frilock commented on pom.xml
> +            <version>5.6.2</version>
А эту версию чего в properties не добавили?) Вроде же написал комментарий об этом

2022-09-20 18:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        log.debug("Количество фильмов: {}", films.size());
Можно в одну строчку 2 лога)

2022-09-20 18:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            log.warn("Попытка обновить несуществующий фильм");
Вроде вы кидаете исключение, а в лог пишете с уровнем warn - не логично. Лучше error (хотя на мой взгляд достаточно просто исключения)

2022-09-20 18:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmUpdateException.java
> +    public FilmUpdateException() {
Думаю что этот конструктор не нужен. Зачем он?

2022-09-20 18:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmValidateException.java
> +    public FilmValidateException() {
Думаю этот конструктор не нужен

2022-09-21 20:35 UTC, Frilock requested changes
Добрый вечер, написал комментарий к вашему вопросу. Так же приложил материалы по работе с pom файлами

2022-09-21 20:35 UTC, Frilock commented on pom.xml
> +            <version>5.6.2</version>
Не не не, в properties вы пишите строчку, например, <junit.version>1.1.1</junit.version>
Потом когда библиотеку добавляете 
<properties>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-engine</artifactId>
        <version>${junit.version}</version>
        <scope>test</scope>
   </properties>
   
   Но работе с пом файлом надо разобраться, это важно
   https://javarush.ru/groups/posts/3119-java-proekt-ot-a-do-ja-vse-chto-vih-khoteli-znatjh-o-maven

2022-09-22 06:07 UTC, Klementor commented
Спасибо большое) Подразобрался))

2022-09-22 12:11 UTC, Frilock approved these changes
Принято

2022-10-14 23:24 UTC, merged