Реализация группового проекта
Klementor/java-filmorate pull request #10
Opened 2022-11-10 18:35 UTC by Klementor

![image](https://user-images.githubusercontent.com/57584673/201178429-bcb0ee4a-312f-40e6-8158-345faca75e99.png)

2022-11-10 20:57 UTC, Frilock requested changes
Необходимо в файл README добавить информацию о выбранных и реализованных вами задач.

2022-11-11 20:00 UTC, Frilock requested changes
Добрый вечер. Оставил ряд комментариев

2022-11-11 20:00 UTC, Frilock commented on README.md
>  [Посмотреть текстовое представление схемы базы данных можно здесь](src/main/resources/schema.txt)
А что за файл появился в проекте DS_Store? Не встречал до этого

Посмотрел: DS_Store — это файлы в операционной системе Apple OS X, они хранят пользовательские настройки папки, такие как расположение иконок, выбранное фоновое изображение, список файлов. Имя является сокращением от Desktop Services Store.

Я что то не уверен, что он должен на ревью попадать.

2022-11-11 20:00 UTC, Frilock commented on profiles.xml
> +<profilesXml xmlns="http://maven.apache.org/PROFILES/1.0.0"
Для чего Вам эта XMLка?

2022-11-11 20:00 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/controller/DirectorController.java
> +@Slf4j
Лишняя аннотация, не вижу в данном классе использования логгера

2022-11-11 20:00 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/controller/DirectorController.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
По моему достаточно @RequiredArgsConstructor, разве нет?

2022-11-11 20:00 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/controller/GenreController.java
>      @GetMapping()
Лишние пустые скобки

2022-11-11 20:00 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/controller/MpaController.java
>      @GetMapping()
Лишние пустые скобки, проверьте в других местах пожалуйста

2022-11-11 20:00 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/controller/ReviewsController.java
> +@Slf4j
Лишняя аннотация. Проверьте пожалуйста остальные классы, писать дальше этот комментарий не буду

2022-11-11 20:00 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/service/DirectorService.java
> +        getDirectorById(id);
Мне кажется наличие нужно проверять тогда уж в самом storage

2022-11-11 20:00 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/service/FilmService.java
> +        if (query != null && !query.isEmpty()) {
Когда к Вам на вход приходит строка и вам нужно проверить не является ли она null или "", то лучше использовать утилиту от apache common 3 - StringUtils.isBlank/isNotBlank

2022-11-11 20:00 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/service/FilmService.java
> +                log.warn("Жанр не найден.");
Хочется какой то более подробный лог, нужно когда лог пишите какие то данные логировать по которым можно сразу определить для какого обьекта был запрос

2022-11-11 20:00 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/service/FilmService.java
> +    public TreeSet<Film> getCommonFilms(int userId, int friendId) {
Вообще правильнее в сигнатурах метода указывать интерфейс, а не конкретную реализацию

2022-11-11 20:00 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/storage/dao/DirectorDbStorage.java
> +    public static class DirectorMapper implements RowMapper<Director> {
Предлагаю мапперы вынести в отдельный слой, то есть все вложенные классы вынести туда. Просто так гораздо легче будет ориентироваться по коду

2022-11-11 20:00 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        StringBuilder sb = new StringBuilder();
Предлагаю запросы писать в каком то одном формате, у вас везде просто весь запрос в 1 строку, которую довольно просто читать. Тут сделали через StringBuilder. Идея использовать StringBuilder, чтобы оптимизировать работу со строками похвальна, но тут в целом конкатенаций не особо много и чтобы было более читаемо лучше сделать запрос как и другие в одну строчку =)

2022-11-11 20:00 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +            String sqlQuery = "SELECT FILM.id, " +
А зачем все поля перечислять? почему ни как везде через обычную *

2022-11-14 16:56 UTC, Klementor commented on src/main/java/com/yandex/practicum/filmorate/service/DirectorService.java
> +        getDirectorById(id);
Мне наоборот казалось, что в storage не должно быть проверок и лучше, чтобы они были в service. Тут как раз есть уже готовый для этого метод, удобненько)

2022-11-14 17:11 UTC, Klementor commented on src/main/java/com/yandex/practicum/filmorate/storage/dao/DirectorDbStorage.java
> +    public static class DirectorMapper implements RowMapper<Director> {
Тогда Heap будет засоряться мапперами, а так они у нас статические и не будут плодиться лишний раз

2022-11-15 15:53 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/service/DirectorService.java
> +        getDirectorById(id);
Соглашусь, смутило название метода, было бы приятнее как то - existDirectorById, и метод boolean можно было бы сделать, и если false, то бы исключение кидали. Но в целом это детали реализации, не суть важно

2022-11-15 15:56 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/storage/dao/DirectorDbStorage.java
> +    public static class DirectorMapper implements RowMapper<Director> {
Этот момент не очень понял, если так за производительность боретесь, то можно было бы маппер спринговым бином сделать и инжектить его в класс. В целом это было просто мое пожелание, поскольку так приложение казалось более слабосвязанным. Был бы дополнительный слой для мапперов .

2022-11-15 16:08 UTC, Frilock requested changes
Добрый вечер, в целом молодцы. Написал еще пару комментариев, но в целом они связаны с тем, что где то вы забыли аннотации убрать или где можно упростить проверки

2022-11-15 16:08 UTC, Frilock commented on pom.xml
> +            <version>3.12.0</version>
Версию лучше в properties вынести

2022-11-15 16:08 UTC, Frilock commented on pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Файл DS_Store суньте в gitignore

2022-11-15 16:08 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/service/DirectorService.java
> +@Slf4j
Вроде как опять же лишняя аннотация

2022-11-15 16:08 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/service/DirectorService.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
По моему это onConstructor_ = @Autowired дефолтный параметр, и можно просто RequiredArgsConstructor

2022-11-15 16:08 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/service/ReviewsService.java
> +        if (review.getContent() == null || review.getContent().isBlank()) {
StringUtils.isBlank

2022-11-15 16:08 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/service/ReviewsService.java
> +@Slf4j
Лишняя аннотация

2022-11-15 16:08 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/service/ReviewsService.java
> +        int filmId = -1;
Если я правильно понимаю, вы заведомо инициализируете кривым значением, чтоб если 
if (filmIdStr != null) {
            filmId = Integer.parseInt(filmIdStr);
        }
        не отработает, вы дальше ошибку получили?
        Если так, то идея не очень, лучше сразу тут проверяйте и бросайте исключение. Инициализировать поле кривыми данными не очень хорошая практика

2022-11-15 16:08 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/service/UserService.java
>  @Slf4j
Вроде опять же, не используется

2022-11-15 16:08 UTC, Frilock commented on src/main/java/com/yandex/practicum/filmorate/storage/FilmStorage.java
> +    TreeSet<Film> getCommonFilms(int userId, int friendId);
В сигнатуре метода лучше интерфейс указывать, а не реализацию, это хорошая практика

2022-11-16 12:55 UTC, Frilock approved these changes
Принято, поздравляю с возможно первым, успешным опытом командной разработки. Успехов в дальнейшем

2023-09-18 10:07 UTC, merged