Add database
Klementor/java-filmorate pull request #5
Opened 2022-10-30 11:58 UTC by Klementor

2022-10-30 16:26 UTC, Frilock requested changes
добрый вечер, оставил ряд комментариев к работе, жду новую версию, будут вопросы пишите

2022-10-30 16:26 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/film/Film.java
> +package ru.yandex.practicum.filmorate.model.film;
Мне кажется тут создание пакетов внутри папки model уже излишни, хотя конечно, на ваше усмотрение

2022-10-30 16:26 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmDbService.java
> +    public FilmDbService(FilmDao filmDao,
Чтобы такие огромные конструкторы не писать, можно на класс повесить аннотацию от lombok - RequiredArgsConstructor и убрать конструктор тогда

2022-10-30 16:26 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmDbService.java
> +            throw new NotFoundException("Введены неверные данные");
Давайте тогда добавим e.getMessage, чтобы яснее было

2022-10-30 16:26 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
>  package ru.yandex.practicum.filmorate.service.film;
У Вас по ТЗ кстати должна в проекте лежать схема БД в виде png файла

2022-10-30 16:26 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/like/LikeDaoImpl.java
> +    static public class LikeMapper implements RowMapper<Like> {
Давайте мапперы в отдельный слой вынесем, так просто проще будет по коду ориентироваться

2022-10-30 16:26 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/user/UserDaoImpl.java
> +            user.setBirthday(rs.getDate("birthday").toLocalDate());
rs.getDate("birthday") , а null не вернет? Вы NPE не получите?

2022-10-30 16:26 UTC, Frilock commented on src/main/resources/data.sql
> +MERGE INTO genres (genre_id, name)
А почему не просто insert?

2022-10-30 16:26 UTC, Frilock commented on src/main/resources/schema.sql
> +    name         VARCHAR NOT NULL,
Смотрите, общий комментарий по скрипту и модели данных. Вы когда архитектуру БД планируете, нужно продумать размерность полей, то есть, например, поле код не должно иметь стандартный размер в 255, а его можно сделать, например, в 50 символов, а вот для описание нужно больше места, поэтому логичнее под данную колонку выделить, например, 1000. 
Кроме того, после того как Вы все указали в скрипте, тоже самое нужно сделать в аннотации Column для классов моделей. Указать размерность поля, а также дополнительные флаги, например, nullable = false.

2022-10-30 17:32 UTC, Klementor commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
>  package ru.yandex.practicum.filmorate.service.film;
![image](https://user-images.githubusercontent.com/57584673/198892689-af13b776-e114-480c-932a-a5a845862b04.png)

2022-10-30 20:05 UTC, Klementor commented
Я закинул исправленный вариант, но он не прошел тесты из-за nonull. Я решил не париться и просто их удалил потому что смысла особо проверять нет

2022-10-31 09:16 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
>  package ru.yandex.practicum.filmorate.service.film;
Странно, на ревью не отображается. Забыл указать - в файле README.md должна быть ссылка на файл диаграммы.

2022-10-31 09:19 UTC, Klementor commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
>  package ru.yandex.practicum.filmorate.service.film;
![image](https://user-images.githubusercontent.com/57584673/198974127-145df0fe-e101-4ea7-8f87-c85eecd450af.png)
Так а она там есть

2022-10-31 09:20 UTC, Klementor commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
>  package ru.yandex.practicum.filmorate.service.film;
У меня все отображается, не знаю

2022-10-31 09:37 UTC, Klementor commented
Я попробовал ссылку поменять на фотку со структурой бд, но она иначе не отображается, у меня 0 идей почему так получилось, что вы не видите. Попросил знакомого зайти посмотреть, у него все отображается

2022-10-31 09:38 UTC, Frilock approved these changes
Принято

2022-10-31 09:38 UTC, Frilock commented on pom.xml
> +        <jdbc.version>2.7.5</jdbc.version>
Название путает как то...лучше spring-data-jdbc.version, но это минор конечно

2022-10-31 09:38 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/rating/RatingDbService.java
> +
Лишняя строчка пустая

2022-11-04 07:25 UTC, merged